import { SocialPlatform } from "@/types/profile";

export const PLATFORM_CONFIG: Record<
  SocialPlatform,
  { label: string; color: string }
> = {
  discord: { label: "Discord", color: "#5865F2" },
  twitter: { label: "Twitter / X", color: "#ffffff" },
  instagram: { label: "Instagram", color: "#E4405F" },
  youtube: { label: "YouTube", color: "#FF0000" },
  tiktok: { label: "TikTok", color: "#ffffff" },
  twitch: { label: "Twitch", color: "#9146FF" },
  github: { label: "GitHub", color: "#ffffff" },
  spotify: { label: "Spotify", color: "#1DB954" },
  applemusic: { label: "Apple Music", color: "#FA243C" },
  linkedin: { label: "LinkedIn", color: "#0A66C2" },
  facebook: { label: "Facebook", color: "#1877F2" },
  telegram: { label: "Telegram", color: "#26A5E4" },
  whatsapp: { label: "WhatsApp", color: "#25D366" },
  soundcloud: { label: "SoundCloud", color: "#FF5500" },
  reddit: { label: "Reddit", color: "#FF4500" },
  pinterest: { label: "Pinterest", color: "#E60023" },
  threads: { label: "Threads", color: "#ffffff" },
  snapchat: { label: "Snapchat", color: "#FFFC00" },
  kick: { label: "Kick", color: "#53FC18" },
  steam: { label: "Steam", color: "#66C0F4" },
  roblox: { label: "Roblox", color: "#ffffff" },
  epicgames: { label: "Epic Games", color: "#ffffff" },
  xbox: { label: "Xbox", color: "#107C10" },
  playstation: { label: "PlayStation", color: "#0070D1" },
  nintendo: { label: "Nintendo", color: "#E60012" },
  minecraft: { label: "Minecraft", color: "#5D7C16" },
  battlenet: { label: "Battle.net", color: "#148EFF" },
  riotgames: { label: "Riot Games", color: "#D32936" },
  paypal: { label: "PayPal", color: "#00457C" },
  gitlab: { label: "GitLab", color: "#FC6D26" },
  bluesky: { label: "Bluesky", color: "#0085FF" },
  patreon: { label: "Patreon", color: "#FF424D" },
  kofi: { label: "Ko-fi", color: "#FF6433" },
  signal: { label: "Signal", color: "#3A76F0" },
  vk: { label: "VK", color: "#0077FF" },
  email: { label: "Email", color: "#a855f7" },
  website: { label: "Website", color: "#a855f7" },
  custom: { label: "Enlace personalizado", color: "#a855f7" },
};
